# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-10 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPopular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaType',
            field=models.CharField(choices=[('MOVIE', 'Movie'), ('TV_SHOW', 'Tv Show')], max_length=255),
        ),
        migrations.AddField(
            model_name='mostpopular',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BestApp.Media', unique=True),
        ),
    ]
