# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-10 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('BestApp', '0002_auto_20210111_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BestApp.Media', unique=True)),
            ],
        ),
    ]
