# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-11 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestApp', '0003_recent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knownFor', models.CharField(max_length=255)),
            ],
        ),
    ]
