# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-11 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestApp', '0003_auto_20210112_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='name',
            field=models.CharField(max_length=255)
        ),
        migrations.AddField(
            model_name='cast',
            name='photo',
            field=models.URLField(unique=True)
        ),
    ]
