# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-10 17:07
from __future__ import unicode_literals

import BestApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.DateField()),
                ('rating', models.IntegerField()),
                ('poster', models.URLField(unique=True)),
                ('description', models.CharField(max_length=800)),
                ('mediaType', models.CharField(choices=[(BestApp.models.MediaType('Movie'), 'Movie'),
                                                        (BestApp.models.MediaType('Tv Show'), 'Tv Show')],
                                               max_length=255)),
            ],
        ),
    ]
