# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-19 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(null=True, unique=True),
        ),
    ]
