# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-19 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestApp', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='photo',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='poster',
            field=models.URLField(null=True, unique=True),
        ),
    ]
